// Date: 17-9-2012 7:20:38
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package DecoMod;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelParticleMachine extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer button;
    ModelRenderer screen;
    ModelRenderer Plate1;
    ModelRenderer Plate2;
    ModelRenderer Plate3;
    ModelRenderer Plate4;
  
  public ModelParticleMachine()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(0F, 0F, 0F, 12, 10, 12);
      base.setRotationPoint(-6F, 13F, -6F);
      base.setTextureSize(64, 32);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      button = new ModelRenderer(this, 0, 22);
      button.addBox(0F, 0F, 0F, 2, 2, 1);
      button.setRotationPoint(-5F, 11F, -7F);
      button.setTextureSize(64, 32);
      button.mirror = true;
      setRotation(button, 0F, 0F, 0F);
      screen = new ModelRenderer(this, 7, 22);
      screen.addBox(0F, 0F, 0F, 6, 6, 1);
      screen.setRotationPoint(-3F, 14F, -7F);
      screen.setTextureSize(64, 32);
      screen.mirror = true;
      setRotation(screen, 0F, 0F, 0F);
      Plate1 = new ModelRenderer(this, 37, 6);
      Plate1.addBox(0F, 0F, 0F, 12, 4, 1);
      Plate1.setRotationPoint(-6F, 9F, -6F);
      Plate1.setTextureSize(64, 32);
      Plate1.mirror = true;
      setRotation(Plate1, 0F, 0F, 0F);
      Plate2 = new ModelRenderer(this, 40, 17);
      Plate2.addBox(0F, 0F, 0F, 1, 4, 11);
      Plate2.setRotationPoint(-6F, 9F, -5F);
      Plate2.setTextureSize(64, 32);
      Plate2.mirror = true;
      setRotation(Plate2, 0F, 0F, 0F);
      Plate3 = new ModelRenderer(this, 40, 17);
      Plate3.addBox(0F, 0F, 0F, 1, 4, 11);
      Plate3.setRotationPoint(5F, 9F, -5F);
      Plate3.setTextureSize(64, 32);
      Plate3.mirror = true;
      setRotation(Plate3, 0F, 0F, 0F);
      Plate4 = new ModelRenderer(this, 38, 0);
      Plate4.addBox(0F, 0F, 0F, 10, 4, 1);
      Plate4.setRotationPoint(-5F, 9F, 5F);
      Plate4.setTextureSize(64, 32);
      Plate4.mirror = true;
      setRotation(Plate4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    base.render(f5);
    button.render(f5);
    screen.render(f5);
    Plate1.render(f5);
    Plate2.render(f5);
    Plate3.render(f5);
    Plate4.render(f5);
  }
  public void renderModel(float f5)
  {
    base.render(f5);
    button.render(f5);
    screen.render(f5);
    Plate1.render(f5);
    Plate2.render(f5);
    Plate3.render(f5);
    Plate4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
